{
 "title": "ICNP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of UEs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "number_of_ues", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Resource allocation index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "index", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "total_bandwidth_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bandwidth Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "bandwidth_allocation", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "cpu_allocation", "legendFormat": "__auto" }
   ]
  }
 ]
}