apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../srsue-live

configMapGenerator:
  - name: ue1-configmap
    behavior: merge
    files:
      - config/noise_protocol.py
      - config/noise_channel_control.py
      - config/multi_ue_noise_channel.py
      - config/start_gnu_noise_channel.sh

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: srsran-ue1
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: noise_protocol.py
          path: noise_protocol.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: noise_channel_control.py
          path: noise_channel_control.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: multi_ue_noise_channel.py
          path: multi_ue_noise_channel.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: start_gnu_noise_channel.sh
          path: start_gnu_noise_channel.sh
          mode: 0755
