apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../srsue

configMapGenerator:
  - name: ue1-configmap
    behavior: merge
    files:
      - config/fixed_channel.py
      - config/fixed_three_path.json
      - config/fixed_three_path_stress.json
      - config/multi_ue_fixed_channel.py
      - config/start_gnu_fixed_channel.sh
      - config/start_gnu_multipath.sh

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: srsran-ue1
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: fixed_channel.py
          path: fixed_channel.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: fixed_three_path.json
          path: fixed_three_path.json
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: fixed_three_path_stress.json
          path: fixed_three_path_stress.json
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: multi_ue_fixed_channel.py
          path: multi_ue_fixed_channel.py
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: start_gnu_fixed_channel.sh
          path: start_gnu_fixed_channel.sh
          mode: 0755
      - op: add
        path: /spec/template/spec/volumes/0/configMap/items/-
        value:
          key: start_gnu_multipath.sh
          path: start_gnu_multipath.sh
          mode: 0755
